Enhance collection.js and testing scenario

diff --git a/.github/workflows/github-ci.yml b/.github/workflows/github-ci.yml
--- a/.github/workflows/github-ci.yml
+++ b/.github/workflows/github-ci.yml
@@ -114,13 +114,34 @@ jobs:
         run: |
           npm install -g newman newman-reporter-htmlextra
 
+      - name: Generate JWT Token
+        id: generate_token
+        run: |
+          # Make POST request to obtain token
+          BEARER_TOKEN_RESPONSE=$(curl -s -X POST "${{ vars.BASE_URL_OAUTH }}" \
+            -H "Content-Type: application/json" \
+            -d '{"grant_type": "'"${{ secrets.GRANT_TYPE }}"'", "client_id": "'"${{ secrets.CLIENT_ID }}"'", "client_secret": "'"${{ secrets.CLIENT_SECRET }}"'"}')
+
+          # Extract access_token using jq
+          BEARER_TOKEN=$(echo $BEARER_TOKEN_RESPONSE | jq -r '.access_token')
+
+          # Check if token was retrieved successfully
+          if [ "$BEARER_TOKEN" == "null" ] || [ -z "$BEARER_TOKEN" ]; then
+            echo "Failed to retrieve access token."
+            echo "Response: $BEARER_TOKEN_RESPONSE"
+            exit 1
+          fi
+
+          echo "TOKEN=$TOKEN" >> $GITHUB_ENV
+
       # Prepare environment.json
       # Inject CLIENT_ID and CLIENT_SECRET into environment.json (you need a template environment.json with placeholders)
       - name: Prepare environment for tests
         run: |
           # The template is at services/phl-products/tests/postman/environment-template.tpl
-          # and contains placeholders like CLIENT_ID_PLACEHOLDER and CLIENT_SECRET_PLACEHOLDER
-          sed "s/CLIENT_ID_PLACEHOLDER/${{ secrets.PRODUCTS_CLIENT_ID }}/g; s/CLIENT_SECRET_PLACEHOLDER/${{ secrets.PRODUCTS_CLIENT_SECRET }}/g" services/${{ vars.PRODUCTS_SVC_NAME }}/tests/postman/environment-template.tpl > services/${{ vars.PRODUCTS_SVC_NAME }}/tests/postman/environment.json
+          # and contains placeholders like {{ BEARER_TOKEN }} and {{ BASE_URL }}
+          sed "s/{{ BEARER_TOKEN }}/${{ env.BEARER_TOKEN }}/g"; s/{{ BASE_URL }}/${{ vars.BASE_URL }}/g" services/${{ env.PRODUCTS_SVC_NAME }}/tests/postman/environment-template.tpl > services/${{ vars.PRODUCTS_SVC_NAME }}/tests/postman/environment.json
+
 
       - name: Run Newman Tests
         run: |
